import * as THREE from "three";
import { playSound } from "./audio";
import { updateBot, type Bot } from "./bots";
import { paintCrosshair } from "./crosshair";
import { DesktopInput } from "./input";
import { buildIronYard } from "./maps";
import { ArenaNetwork, arenaSocketUrl, type ArenaNetworkEvent } from "./networking";
import { FpsPlayer } from "./player";
import { Recoil } from "./recoil";
import { createFighter, createRenderer, createWeapon } from "./rendering";
import { crosshairCode, importCrosshair, loadSettings, saveSettings } from "./settings";
import { WeaponState, type WeaponId } from "./weapons";

type ArenaResult = { won: boolean; accuracy: number; eliminations: number };
let stop: (() => void) | undefined;
export function arenaView() { const online = Boolean(arenaSocketUrl()); return `<section class="arena-game"><div class="arena-heading"><p class="eyebrow">DESKTOP FPS VERTICAL SLICE</p><h1>IRON YARD</h1><p>Original industrial yard. Practice against a bot or open a lightweight 1v1 room.</p></div><div class="arena-lobby"><p id="arena-connection">PRACTICE IS READY</p><div><button id="arena-bot" class="primary">PLAY TRAINING BOT</button>${online ? `<button id="arena-create" class="outline">CREATE 1V1</button><label>ROOM <input id="arena-room-code" maxlength="6" /></label><button id="arena-join" class="outline">JOIN</button>` : `<small>Set VITE_ARENA_SERVER_URL to enable 1v1 rooms.</small>`}</div></div><div class="arena-loadout"><button class="outline" data-arena-loadout="rifle" aria-pressed="true"><b>MESA RIFLE</b><span>30 rounds · automatic · patterned recoil</span></button><button class="outline" data-arena-loadout="pistol" aria-pressed="false"><b>RANGER PISTOL</b><span>12 rounds · precise sidearm</span></button></div><div class="arena-frame"><div id="arena-canvas"></div><button id="arena-lock" class="arena-lock" hidden>CLICK TO PLAY</button><div id="arena-crosshair" class="arena-reticle"><i></i><b></b><em></em></div><div class="arena-status"><span id="arena-health">HEALTH 100</span><span id="arena-ammo">30 / 90</span><span id="arena-rival">BOT 100</span></div><div id="arena-message" class="arena-message">SELECT TRAINING OR CREATE A ROOM</div><div id="arena-pause" class="arena-pause" hidden><b>PAUSED</b><span>Click the yard to resume</span></div></div><div class="arena-controls"><button id="arena-fire" class="primary" disabled>FIRE</button><button id="arena-reload" class="outline" disabled>RELOAD</button><button id="arena-ads" class="outline" disabled>AIM</button></div><details class="arena-settings"><summary>RETICLE & MOUSE SETTINGS</summary><label>SENSITIVITY <input id="fps-sensitivity" type="range" min="0.001" max="0.006" step="0.0002" /></label><label>COLOR <input id="cross-color" type="color" /></label><label>SIZE <input id="cross-size" type="range" min="2" max="18" /></label><label>IMPORT <input id="cross-import" placeholder="reticle code" /></label><button id="cross-share" class="outline">COPY RETICLE CODE</button></details><p class="trace-hint">WASD MOVE · SHIFT SPRINT · CTRL CROUCH · SPACE JUMP · MOUSE AIM · CLICK FIRE · R RELOAD · RIGHT CLICK AIM · ESC PAUSE</p><p class="arena-local-note">Offline training has a real movement, aiming, damage, respawn, and score loop.</p></section>`; }

export function mountArena(onComplete: (result: ArenaResult) => void) {
  stop?.(); const host=document.querySelector<HTMLElement>("#arena-canvas"), message=document.querySelector<HTMLElement>("#arena-message"), lock=document.querySelector<HTMLButtonElement>("#arena-lock"), health=document.querySelector<HTMLElement>("#arena-health"), ammo=document.querySelector<HTMLElement>("#arena-ammo"), rival=document.querySelector<HTMLElement>("#arena-rival"), reticle=document.querySelector<HTMLElement>("#arena-crosshair"), pause=document.querySelector<HTMLElement>("#arena-pause"); if (!host||!message||!lock||!health||!ammo||!rival||!reticle||!pause) return;
  const settings=loadSettings(), scene=new THREE.Scene(), camera=new THREE.PerspectiveCamera(settings.fov,16/9,.05,90), renderer=createRenderer(host), colliders=buildIronYard(scene), player=new FpsPlayer(camera,colliders), weapon=new WeaponState(), recoil=new Recoil(), network=new ArenaNetwork(); scene.add(camera); scene.background=new THREE.Color("#9aabb0"); scene.fog=new THREE.Fog("#9aabb0",24,58); scene.add(new THREE.HemisphereLight("#dce9ed","#343334",2)); const sun=new THREE.DirectionalLight("#ffe0bb",3); sun.position.set(-10,16,8); sun.castShadow=true; sun.shadow.mapSize.set(1024,1024); scene.add(sun); const gun=createWeapon(camera); const muzzle=new THREE.PointLight("#ffbd72",0,4); camera.add(muzzle);
  let bot:Bot|undefined, remote:THREE.Group|undefined, seat:"host"|"guest"|undefined, online=false, active=false, aiming=false, receivedSpawn=false, shots=0,hits=0,kills=0,lastSync=0,lastFrame=performance.now(); const raycaster=new THREE.Raycaster();
  const updateHud=()=>{ health.textContent=`HEALTH ${Math.ceil(player.health)}`; ammo.textContent=weapon.reloading?"RELOADING":`${weapon.ammo} / ${weapon.reserve}`; rival.textContent=online?"RIVAL LIVE":`BOT ${Math.max(0,Math.ceil(bot?.health??0))}`; };
  const spawnBot=()=>{ const group=createFighter("#6a4e47"); group.position.set(10,0,-9); scene.add(group); bot={group,health:100,nextThink:0,velocity:new THREE.Vector3(),spawn:group.position.clone()}; };
  const start=(isOnline=false)=>{ online=isOnline; if(online&&bot){scene.remove(bot.group);bot=undefined;} if(!online&&!bot)spawnBot(); active=true; lock.hidden=false; message.textContent=online?"RIVAL CONNECTED. CLICK TO PLAY.":"TRAINING BOT ACTIVE. CLICK TO PLAY."; updateHud(); };
  const tracer=(from:THREE.Vector3,to:THREE.Vector3)=>{ const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints([from,to]),new THREE.LineBasicMaterial({color:"#ffd28a"})); scene.add(line); setTimeout(()=>{scene.remove(line);line.geometry.dispose();(line.material as THREE.Material).dispose();},70); };
  const damageBot=(head:boolean)=>{ if(!bot)return; bot.health-=head?weapon.spec.headshot:weapon.spec.damage; hits++; playSound("bottle"); if(bot.health<=0){kills++; bot.health=100; bot.group.position.copy(bot.spawn); message.textContent="ELIMINATION. BOT RESPAWNED.";} updateHud(); };
  const fire=()=>{ const now=performance.now(); if(!active||document.pointerLockElement!==renderer.domElement||!weapon.canFire(now))return; weapon.fired(now); shots++; recoil.kick(weapon.spec.recoil,weapon.spec.recoil*.55); muzzle.intensity=5; setTimeout(()=>muzzle.intensity=0,35); const direction=new THREE.Vector3();camera.getWorldDirection(direction); direction.x+=(Math.random()-.5)*weapon.spec.spread;direction.y+=(Math.random()-.5)*weapon.spec.spread; tracer(camera.position.clone(),camera.position.clone().addScaledVector(direction,35)); if(online) network.send({type:"shot",loadout:weapon.spec.id==="rifle"?"carbine":"sidearm",yaw:player.yaw,pitch:player.pitch}); else if(bot){raycaster.set(camera.position,direction.normalize());const hit=raycaster.intersectObject(bot.group,true)[0];if(hit)damageBot(hit.object.position.y>.9);} playSound("shot");updateHud(); };
  const input=new DesktopInput(renderer.domElement,(x,y)=>player.look(x,y,settings.sensitivity),fire);
  const request=()=>{ if(active) renderer.domElement.requestPointerLock().catch(()=>message.textContent="POINTER LOCK WAS BLOCKED. CLICK AGAIN."); };
  const resize=()=>{const b=host.getBoundingClientRect();renderer.setSize(b.width,b.height,false);camera.aspect=b.width/b.height;camera.updateProjectionMatrix();}; const observer=new ResizeObserver(resize);observer.observe(host);resize();paintCrosshair(reticle,settings.crosshair);
  const beginOnline=()=>{active=false;lock.hidden=true;if(bot){scene.remove(bot.group);bot=undefined;}online=true;};
  const reload=()=>weapon.reload(updateHud); document.querySelector("#arena-bot")?.addEventListener("click",()=>start()); document.querySelector("#arena-create")?.addEventListener("click",()=>{beginOnline();if(network.connect("create","",event=>handleNetwork(event)))message.textContent="CREATING ROOM...";});document.querySelector("#arena-join")?.addEventListener("click",()=>{const code=document.querySelector<HTMLInputElement>("#arena-room-code")?.value.trim().toUpperCase()??"";if(code.length===6){beginOnline();if(network.connect("join",code,event=>handleNetwork(event)))message.textContent="JOINING ROOM...";}});
  const applySpawn=(value:{x:number;z:number;yaw:number;pitch:number;health:number})=>{camera.position.set(value.x*8,1.7,1-value.z*12);player.yaw=value.yaw;player.pitch=value.pitch;player.velocity.set(0,0,0);player.health=value.health;receivedSpawn=true;};
  const handleNetwork=(event: ArenaNetworkEvent)=>{ if(event.type==="joined"){seat=event.seat;message.textContent=`ROOM ${event.room}. WAITING FOR RIVAL.`;} if(event.type==="state"&&event.started&&!active)start(true); if(event.type==="state"&&active&&seat){const own=event.players[seat], other=event.players[seat==="host"?"guest":"host"]; if(!receivedSpawn)applySpawn(own); if(!remote){remote=createFighter("#405e6a");scene.add(remote);} remote.position.set(other.x*8,0,1-other.z*12);player.health=own.health;updateHud();} if(event.type==="shot")message.textContent=event.hit?"HIT CONFIRMED":"SHOT WIDE"; if(event.type==="respawn"){if(event.seat===seat)applySpawn(event.player);message.textContent=event.seat===seat?"YOU RESPAWNED":"RIVAL RESPAWNED";} if(event.type==="result"){active=false;message.textContent="ROUND COMPLETE";onComplete({won:event.winner===seat,accuracy:shots?Math.round(hits/shots*100):0,eliminations:kills});} if(event.type==="error")message.textContent=event.message; };
  const onKeyDown=(event:KeyboardEvent)=>{if(event.code==="KeyR")reload();}; const onLockChange=()=>{pause.hidden=document.pointerLockElement===renderer.domElement||!active;lock.hidden=document.pointerLockElement===renderer.domElement;};
  document.querySelectorAll<HTMLButtonElement>("[data-arena-loadout]").forEach(button=>button.addEventListener("click",()=>{weapon.select(button.dataset.arenaLoadout as WeaponId);document.querySelectorAll("[data-arena-loadout]").forEach(item=>item.setAttribute("aria-pressed",String(item===button)));updateHud();})); document.querySelector("#arena-fire")?.addEventListener("click",fire);document.querySelector("#arena-reload")?.addEventListener("click",reload);document.querySelector("#arena-ads")?.addEventListener("click",()=>aiming=!aiming);lock.addEventListener("click",request);renderer.domElement.addEventListener("click",request);renderer.domElement.addEventListener("contextmenu",event=>{event.preventDefault();aiming=!aiming;});document.addEventListener("keydown",onKeyDown);document.addEventListener("pointerlockchange",onLockChange);
  const sensitivity=document.querySelector<HTMLInputElement>("#fps-sensitivity"), color=document.querySelector<HTMLInputElement>("#cross-color"),size=document.querySelector<HTMLInputElement>("#cross-size");if(sensitivity){sensitivity.value=String(settings.sensitivity);sensitivity.oninput=()=>{settings.sensitivity=Number(sensitivity.value);saveSettings(settings);};}if(color){color.value=settings.crosshair.color;color.oninput=()=>{settings.crosshair.color=color.value;paintCrosshair(reticle,settings.crosshair);saveSettings(settings);};}if(size){size.value=String(settings.crosshair.size);size.oninput=()=>{settings.crosshair.size=Number(size.value);paintCrosshair(reticle,settings.crosshair);saveSettings(settings);};}document.querySelector("#cross-share")?.addEventListener("click",()=>navigator.clipboard?.writeText(crosshairCode(settings.crosshair)));document.querySelector<HTMLInputElement>("#cross-import")?.addEventListener("change",event=>{const value=importCrosshair((event.target as HTMLInputElement).value);if(value){settings.crosshair=value;paintCrosshair(reticle,value);saveSettings(settings);}});
  let raf=0; const frame=(now:number)=>{const dt=Math.min(.05,(now-lastFrame)/1000);lastFrame=now;if(active){player.update(dt,input);recoil.update(dt);gun.rotation.x=-recoil.pitch;gun.rotation.y=recoil.yaw;const targetFov=aiming?58:settings.fov;camera.fov+=(targetFov-camera.fov)*Math.min(1,dt*12);camera.updateProjectionMatrix();if(bot)updateBot(bot,camera.position,now,dt,(from,dir)=>{tracer(from,camera.position);if(Math.random()<.18){player.health=Math.max(0,player.health-12);message.textContent="YOU WERE HIT";if(!player.health){player.health=100;camera.position.set(-10,1.7,9);message.textContent="RESPAWNED";}updateHud();}});if(online&&now-lastSync>67){lastSync=now;network.send({type:"state",x:camera.position.x/8,z:(1-camera.position.z)/12,yaw:player.yaw,pitch:player.pitch});}}renderer.render(scene,camera);raf=requestAnimationFrame(frame);};raf=requestAnimationFrame(frame);start();
  stop=()=>{cancelAnimationFrame(raf);network.close();input.destroy();observer.disconnect();document.exitPointerLock?.();document.removeEventListener("keydown",onKeyDown);document.removeEventListener("pointerlockchange",onLockChange);renderer.dispose();scene.traverse(object=>{const mesh=object as THREE.Mesh;mesh.geometry?.dispose();if(Array.isArray(mesh.material))mesh.material.forEach(material=>material.dispose());else mesh.material?.dispose();});host.replaceChildren();stop=undefined;}; return stop;
}
export function unmountArena(){stop?.();}
